import dbConnect from "@/DB/connect";
import "./globals.css";
import { Inter } from "next/font/google";
import Nav from "@/Components/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "بيت المعلم",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // await dbConnect();
  return (
    <html lang="en" dir="rtl">
      <body className="flex flex-col min-h-screen bg-offWhite text-text">
        <Nav />
        <main className="grow">{children}</main>
      </body>
    </html>
  );
}
