import dbConnect from "@/DB/connect";
import "./globals.css";
import { ToastContainer } from "react-toastify";

export const metadata = {
  title: "بيت المعلم",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl" className="scroll-smooth ">
      <body className="flex flex-col min-h-screen bg-offWhite text-text">
        <ToastContainer />
        <main className=" grow">{children}</main>
      </body>
    </html>
  );
}
